# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseurl=https://ppmapi20240106013303.azurewebsites.net/
@accessToken=YourBearerAccessToken
@refreshToken=YourBearerRefreshToken

POST {{baseurl}}gen-pwd
Content-Type: application/json

{
  "title": "example_title",
  "masterKey": "example_key"
}

###

POST {{baseurl}}register
Content-Type: application/json

{
  "username": "testname",
  "email": "test@testmail.com",
  "password": "Test@123"
}

###

POST {{baseurl}}login
Content-Type: application/json

{
  "email": "test@testmail.com",
  "password": "Test@123"
}

###

POST {{baseurl}}auth/gen-pwd
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "title"
}

###

GET {{baseurl}}manage/info
Authorization: Bearer {{accessToken}}

###

GET {{baseurl}}saved-sites
Authorization: Bearer {{accessToken}}


###

POST {{baseurl}}refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

DELETE {{baseurl}}auth/delete-site
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Google"
}

###

DELETE {{baseurl}}auth/clear-sites
Authorization: Bearer {{accessToken}}

###

