export const baseUrl = 'https://ppmapi20240106013303.azurewebsites.net/'
export const genAuth = 'auth/gen-pwd/'
export const genNoAuth = 'gen-pwd/'
export const getSavedSites = 'saved-sites/'
export const deleteSite = 'auth/delete-site'